#!/usr/bin/env python3
"""Validate and visualize the completed real-model audit."""

import argparse
import json
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load_calls(path):
    with open(path, "r") as f:
        return [json.loads(line) for line in f if line.strip()]


def validate(events, calls, manifest):
    errors = []
    if len(events) != int(manifest["completed_events"]):
        errors.append("event count does not match manifest")
    if len(calls) != int(manifest["completed_api_calls"]):
        errors.append("call count does not match manifest")
    if manifest["http_request_attempts_including_retries"] > \
            manifest["audit_config"]["max_total_api_requests"]:
        errors.append("request budget exceeded")
    if any(x["status"] != "completed" for x in calls):
        errors.append("not every response completed")
    if any(int(x["retry_index"]) != 0 for x in calls):
        errors.append("unexpected API retry")
    if any(int(x["input_tokens"]) + int(x["output_tokens"]) !=
           int(x["total_tokens"]) for x in calls):
        errors.append("token accounting mismatch")
    if len(set(x["response_id"] for x in calls)) != len(calls):
        errors.append("duplicate response ID")
    if len(set(x["request_id"] for x in calls)) != len(calls):
        errors.append("duplicate request ID")

    by_event = {}
    for item in calls:
        by_event.setdefault(item["event_id"], []).append(item)
    for _, event in events.iterrows():
        rows = by_event.get(event.event_id, [])
        expected = 3 + int(event.aai_rounds) + 1
        if len(rows) != expected:
            errors.append("wrong call count for %s" % event.event_id)
        roles = [x["agent_role"] for x in rows]
        if sum(r == "oran" for r in roles) != 1 or \
           sum(r == "compute" for r in roles) != 1 or \
           sum(r == "cn" for r in roles) != 1 or \
           sum(r == "one_shot" for r in roles) != 1:
            errors.append("wrong role multiplicity for %s" % event.event_id)
        if int(event.aai_api_calls) != 3 + int(event.aai_rounds):
            errors.append("AAI call count mismatch for %s" % event.event_id)

    return errors


def plot(summary, output_base):
    plt.rcParams.update({"font.size": 9, "axes.grid": True,
                         "grid.alpha": 0.25, "savefig.dpi": 300})
    x = np.arange(len(summary))
    width = 0.36
    labels = [str(int(v)) for v in summary.vehicles]
    fig, axes = plt.subplots(1, 3, figsize=(7.2, 2.65))

    axes[0].bar(x - width / 2, summary.mean_aai_event_wall_ms, width,
                label="AAI-CDOS", color="#0072B2")
    axes[0].bar(x + width / 2, summary.mean_oneshot_wall_ms, width,
                label="One-Shot", color="#009E73")
    axes[0].set_title("Real API wall time/event")
    axes[0].set_ylabel("ms")
    axes[0].legend(fontsize=8)

    aai_tokens = summary.mean_aai_input_tokens + summary.mean_aai_output_tokens
    one_tokens = summary.mean_oneshot_input_tokens + summary.mean_oneshot_output_tokens
    axes[1].bar(x - width / 2, aai_tokens, width, color="#0072B2")
    axes[1].bar(x + width / 2, one_tokens, width, color="#009E73")
    axes[1].set_title("Returned usage/event")
    axes[1].set_ylabel("tokens")

    axes[2].bar(x - width / 2, 100 * summary.aai_verifier_acceptance_rate,
                width, color="#0072B2")
    axes[2].bar(x + width / 2, 100 * summary.oneshot_selected_deadline_rate,
                width, color="#009E73")
    axes[2].set_title("Selected-plan feasibility")
    axes[2].set_ylabel("%")
    axes[2].set_ylim(0, 105)

    for ax in axes:
        ax.set_xticks(x)
        ax.set_xticklabels(labels)
        ax.set_xlabel("Connected vehicles")
    fig.tight_layout()
    for ext in ("png", "pdf"):
        fig.savefig(output_base + "." + ext, bbox_inches="tight")
    plt.close(fig)


def write_results_tex(path, events, calls, summary, manifest, total_cost):
    total_input = sum(int(x["input_tokens"]) for x in calls)
    total_output = sum(int(x["output_tokens"]) for x in calls)
    mean_aai_wall = float(events.aai_event_wall_ms.mean())
    mean_one_wall = float(events.oneshot_wall_ms.mean())
    infeasible = events[(events.aai_fallback == True) &
                        (events.aai_estimated_latency_ms > events.deadline_ms)]
    returned = ", ".join(manifest["returned_models"])
    lines = [
        "% Auto-generated by scripts/analyze_llm_audit.py",
        "\\paragraph{Real-model telemetry audit.}",
        ("The bounded audit completed %d orchestration events using %d API "
         "calls without retries. The requested GPT-4o alias resolved to "
         "\\texttt{%s}. The calls consumed %d input and %d output tokens, "
         "corresponding to an estimated standard API cost of \\$%.4f at the "
         "recorded prices. Mean wall time was %.1f~ms per AAI-CDOS event and "
         "%.1f~ms per One-Shot event. " %
         (len(events), len(calls), returned.replace("_", "\\_"), total_input,
          total_output, total_cost, mean_aai_wall, mean_one_wall)),
        ("At 50 vehicles, %d of %d sampled states had no deadline-feasible "
         "candidate even after the minimum-latency fallback; these events "
         "exhausted the three-round verifier budget. This small sampled audit "
         "is reported only as planner telemetry and is not used to form the "
         "network-performance confidence intervals." %
         (len(infeasible), len(events[events.vehicles == 50]))),
        ("Because the measured cloud-API planner wall time exceeds the "
         "0.15--1.0~s application deadlines, the audit does not support "
         "synchronous per-event cloud control. A deployment interpretation "
         "requires asynchronous or precomputed orchestration, or a "
         "substantially lower-latency local serving path."),
    ]
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", default="results/llm_audit")
    args = parser.parse_args()
    input_dir = args.input if os.path.isabs(args.input) else os.path.join(ROOT, args.input)
    events = pd.read_csv(os.path.join(input_dir, "events.csv"))
    summary = pd.read_csv(os.path.join(input_dir, "summary.csv"))
    calls = load_calls(os.path.join(input_dir, "calls.jsonl"))
    with open(os.path.join(input_dir, "run_manifest.json"), "r") as f:
        manifest = json.load(f)
    with open(os.path.join(ROOT, "config", "llm_audit.yaml"), "r") as f:
        audit_cfg = yaml.safe_load(f)["llm_audit"]

    errors = validate(events, calls, manifest)
    total_input = sum(int(x["input_tokens"]) for x in calls)
    total_output = sum(int(x["output_tokens"]) for x in calls)
    total_cost = (total_input * float(audit_cfg["input_usd_per_million_tokens"]) +
                  total_output * float(audit_cfg["output_usd_per_million_tokens"])) / 1e6
    report = {
        "status": "passed" if not errors else "failed",
        "errors": errors,
        "events": len(events),
        "api_calls": len(calls),
        "unique_response_ids": len(set(x["response_id"] for x in calls)),
        "input_tokens": total_input,
        "output_tokens": total_output,
        "estimated_standard_cost_usd": total_cost,
        "fallback_events": int(events.aai_fallback.sum()),
        "minimum_latency_still_infeasible_events": int((
            (events.aai_fallback == True) &
            (events.aai_estimated_latency_ms > events.deadline_ms)).sum()),
    }
    with open(os.path.join(input_dir, "validation.json"), "w") as f:
        json.dump(report, f, indent=2, sort_keys=True)
    plot(summary, os.path.join(ROOT, "figures", "llm_audit_overhead"))
    write_results_tex(os.path.join(ROOT, "paper", "llm_audit_results.tex"),
                      events, calls, summary, manifest, total_cost)
    print(json.dumps(report, indent=2, sort_keys=True))
    if errors:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
